new build script

diff --git a/templates/build_awx_sdist.sh.j2 b/templates/build_awx_sdist.sh.j2
--- a/templates/build_awx_sdist.sh.j2
+++ b/templates/build_awx_sdist.sh.j2
@@ -1,18 +1,46 @@
-#!/usr/bin/env bash
+#!/usr/bin/bash
 
-source /var/awx/venv/bin/activate
-make sdist
-MYWD=`pwd`
+PACKAGEDIR="/tmp/awx/packages"
+PACKAGES=`ls -1 ${PACKAGEDIR} | tr 'A-Z' 'a-z'`
+PREFIX="awxrpm"
 
-tar xvzf ${MYWD}/dist/awx-{{ awx_image_version }}.tar.gz
-
-ln -s /opt/awx-{{ awx_image_version}}/awx/static /var/lib/awx/public/static
-ln -s /opt/awx-{{ awx_image_version}}/awx/templates /var/lib/awx/public/templates
-
-chown -R awx:awx  /var/lib/awx
-
-cd /opt/awx-{{ awx_image_version }}
-
-python setup.py install
+python3 -m venv /tmp/awxrpmvenv
+source /tmp/awxrpmvenv/bin/activate
+pip install --upgrade pip
+pip install spec2scl
+/usr/bin/rm -r /tmp/scl 2>/dev/null 
+mkdir /tmp/scl 2>/dev/null 
 
 
+COUNT=0
+LOOP="TRUE"
+while [[ $LOOP == "TRUE" ]];
+do	
+	LOOP="FALSE"	
+	for PACKAGE in $PACKAGES
+	do
+		echo $PACKAGE
+	
+		cd ${PACKAGEDIR}/${PACKAGE}
+		PACKAGEINFO=`find . -type d -path './*' -prune -print |cut -c 3-`  
+		NAME=`echo $PACKAGEINFO | awk -F'-' '{ print $1 }'`
+		VERS=`echo $PACKAGEINFO | awk -F'-' '{ print $2 }'`
+		cd ${PACKAGEDIR}/${PACKAGE}
+		SPFILE="${HOME}/rpmbuild/SPECS/${PACKAGE}.spec"
+		if [[ -f $SPFILE ]];
+		then
+			rm  /tmp/scl/${PACKAGE}.scl.spec 2>/dev/null 
+			spec2scl $SPFILE > /tmp/scl/${PACKAGE}.scl.spec
+			SRC="${HOME}/rpmbuild/SOURCES/${NAME}-${VERS}.tar.gz"
+			DST="${HOME}/rpmbuild/SOURCES/${PREFIX}-${NAME}-${VERS}.tar.gz"
+			mv $SRC $DST
+			rpmbuild -ba  /tmp/scl/${PACKAGE}.scl.spec --define "scl awxrpm" 
+			if [[ $? == 0 ]];
+			then
+		                echo "$COUNT `date`: $PACKAGE OK: rpm created" >/dev/null 2>&1
+			else
+		                echo "$COUNT `date`: $PACKAGE ERROR: rpm failed" >/dev/null 2>&1
+			fi
+		fi
+	done
+done
